development:
  clients:
    default:
      database: weblinc_sample_plugin_development
      hosts:
        - localhost:27017
  options:
    use_activesupport_time_zone: false
test:
  clients:
    default:
      database: weblinc_sample_plugin_test
      hosts:
        - localhost:27017
      options:
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    use_activesupport_time_zone: false
